[package]
name = "git-lot"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive", "deprecated"] }
git-repository = "0.33.0"
terminal_size = "0.2.3"
textplots = "0.8.0"
